---
name: Build and test nexus-casc-plugin

on:
  push:
    branches: ["**"]

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: 'adopt'
      - run: ./mvnw -B verify --file pom.xml
      - run: mkdir staging && cp target/*.{k,j}ar staging
      - uses: actions/upload-artifact@v4
        with:
          name: nexus-casc-plugin
          path: staging
